sonar.organization=conectagro-usp
sonar.projectKey=ConectAgro-USP_ConectAgro
sonar.projectName=ConectAgro

sonar.sources=server/src,web/src
sonar.tests=server/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**,server/alembic/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=server/coverage.xml
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info
